import type { Metadata } from 'next';
import { Inter, Saira } from 'next/font/google';
import StyledComponentsRegistry from '../lib/styled-copmponents-resgistry';
import './globals.css';
import Header from '@/components/header/Header';

const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  display: 'swap',
});
const saira = Saira({
  variable: '--font-saira',
  subsets: ['latin'],
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${saira.variable} antialiased`}>
        <StyledComponentsRegistry>
          <Header />
          {children}
        </StyledComponentsRegistry>
      </body>
    </html>
  );
}
